name: Run Tests

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21 (manual installation)
        run: |
          sudo apt-get update
          sudo apt-get install -y openjdk-21-jdk

      - name: Install dependencies
        run: mvn install -DskipTests=true

      - name: Run Tests
        run: mvn test

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: target/test-classes
