name: Java CI with Maven

on:
  pull_request:
    branches:
      - main  # Run the workflow on PRs targeting the 'main' branch
  push:
    branches:
      - main  # Run the workflow on pushes to the 'main' branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up JDK 21 (Temurin distribution)
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'   # Use Temurin OpenJDK distribution
          java-version: '21'        # Specify Java version 21

      # Step 3: Cache Maven dependencies
      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2

      # Step 4: Build the project with Maven
      - name: Build with Maven
        run: mvn clean install -DskipTests=true  # Skip tests during the build phase

      # Step 5: Run tests with Maven
      - name: Run tests with Maven
        run: mvn test  # Run tests separately

      # Step 6: Upload test results (Optional)
      - name: Upload Test Results
        if: always()  # Runs this step even if previous steps fail
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: target/surefire-reports
